CREATE TABLE IF NOT EXISTS mpa_rating (
  rating_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
  film_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  description varchar(200),
  release_date date NOT NULL,
  duration bigint NOT NULL,
  rating_id bigint NOT NULL,
  FOREIGN KEY (rating_id) REFERENCES mpa_rating (rating_id)
);

CREATE TABLE IF NOT EXISTS users (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar NOT NULL,
  login varchar NOT NULL,
  name varchar,
  birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
  film_id bigint,
  user_id bigint,
  PRIMARY KEY (film_id, user_id),
  FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS friendship (
  user_id bigint,
  friend_id bigint,
  PRIMARY KEY (user_id, friend_id),
  FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
  FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genre (
  genre_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_genres (
  film_id bigint,
  genre_id bigint,
  PRIMARY KEY (film_id, genre_id),
  FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
  FOREIGN KEY (genre_id) REFERENCES genre (genre_id)
);